version: '3.8'

services:
  client:
    container_name: delivery-client
    build: ./client
    restart: always
    env_file:
      - .env
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    stdin_open: true
    depends_on:
      - api
  api:
      container_name: delivery-api
      build: ./api
      restart: always
      env_file:
        - .env
      volumes:
        - ./api:/usr/src/app/api
        - /usr/src/app/api/node_modules
      ports:
        - ${API_PORT}:${API_PORT}
      depends_on:
        - db
  db:
    container_name: delivery-db
    image: mongo
    restart: always
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: {}